// Auto-generated by generate_training_curves.py
// Source: formality_model
// Checkpoints: checkpoint-5485, checkpoint-10970, checkpoint-16455, checkpoint-21940, checkpoint-27425

#import "@preview/cetz:0.3.4"
#import "@preview/cetz-plot:0.1.1": plot

#let train-loss = (
  (0.0182, 0.463764),
  (0.1094, 0.329622),
  (0.2005, 0.309729),
  (0.2917, 0.296786),
  (0.3829, 0.294398),
  (0.4740, 0.286180),
  (0.5652, 0.286258),
  (0.6563, 0.296452),
  (0.7475, 0.294948),
  (0.8387, 0.279498),
  (0.9298, 0.284135),
  (1.0210, 0.249696),
  (1.1121, 0.251560),
  (1.2033, 0.242858),
  (1.2944, 0.250759),
  (1.3856, 0.259835),
  (1.4768, 0.249146),
  (1.5679, 0.258105),
  (1.6591, 0.247593),
  (1.7502, 0.249788),
  (1.8414, 0.261706),
  (1.9325, 0.258890),
  (2.0237, 0.191710),
  (2.1149, 0.207739),
  (2.2060, 0.211880),
  (2.2972, 0.215529),
  (2.3883, 0.199818),
  (2.4795, 0.209216),
  (2.5706, 0.201952),
  (2.6618, 0.204311),
  (2.7530, 0.215425),
  (2.8441, 0.215406),
  (2.9353, 0.213018),
  (3.0264, 0.167311),
  (3.1176, 0.180717),
  (3.2088, 0.177112),
  (3.2999, 0.171353),
  (3.3911, 0.175916),
  (3.4822, 0.155140),
  (3.5734, 0.173942),
  (3.6645, 0.174551),
  (3.7557, 0.177657),
  (3.8469, 0.175764),
  (3.9380, 0.168633),
  (4.0292, 0.119227),
  (4.1203, 0.144282),
  (4.2115, 0.153593),
  (4.3026, 0.145019),
  (4.3938, 0.163606),
  (4.4850, 0.149250),
  (4.5761, 0.140083),
  (4.6673, 0.155878),
  (4.7584, 0.146942),
  (4.8496, 0.158821),
  (4.9407, 0.157505),
)

#let val-loss = (
  (1.0000, 0.279802),
  (2.0000, 0.241386),
  (3.0000, 0.254321),
  (4.0000, 0.283699),
  (5.0000, 0.310801),
)

#let val-acc = (
  (1.0000, 0.878028),
  (2.0000, 0.897195),
  (3.0000, 0.894414),
  (4.0000, 0.890517),
  (5.0000, 0.889765),
)

#let val-f1 = (
  (1.0000, 0.878319),
  (2.0000, 0.898289),
  (3.0000, 0.896748),
  (4.0000, 0.893320),
  (5.0000, 0.892024),
)

#let epoch-lines = (1.0, 2.0, 3.0, 4.0, 5.0,)
#let best-epoch  = 2.0

#figure(
  grid(
    columns: 1,
    rows: 2,
    gutter: 0.8em,

    // ── Plot 1: Training & validation loss ──────────────────────────────
    cetz.canvas({
      import cetz.draw: *
      plot.plot(
        size: (7, 4),
        x-label: [Epoch],
        y-label: [Loss],
        x-min: 0, x-max: 5.2,
        y-min: 0.1, y-max: 0.49,
        x-tick-step: 1,
        y-tick-step: 0.05,
        legend: "inner-north-east",
        legend-style: (stroke: 0.4pt, padding: 0.3em),
        {
          for e in epoch-lines {
            plot.add-vline(e, style: (stroke: (paint: gray, thickness: 0.4pt, dash: "dashed")))
          }
          plot.add-vline(best-epoch,
            style: (stroke: (paint: rgb("#0F6E56"), thickness: 0.8pt, dash: "dotted")))

          plot.add(
            train-loss,
            label: [Training loss],
            style: (stroke: (paint: rgb("#185FA5"), thickness: 1.2pt)),
            mark: none,
          )
          plot.add(
            val-loss,
            label: [Validation loss],
            style: (stroke: (paint: rgb("#993C1D"), thickness: 1.4pt)),
            mark: "o",
            mark-size: 0.15,
            mark-style: (fill: rgb("#993C1D"), stroke: none),
          )
        }
      )
    }),

    // ── Plot 2: Validation accuracy & F1 ────────────────────────────────
    cetz.canvas({
      import cetz.draw: *
      plot.plot(
        size: (7, 3.5),
        x-label: [Epoch],
        y-label: [Score],
        x-min: 0, x-max: 5.2,
        y-min: 0.87, y-max: 0.91,
        x-tick-step: 1,
        y-tick-step: 0.01,
        legend: "inner-south-east",
        legend-style: (stroke: 0.4pt, padding: 0.3em),
        {
          for e in epoch-lines {
            plot.add-vline(e, style: (stroke: (paint: gray, thickness: 0.4pt, dash: "dashed")))
          }
          plot.add-vline(best-epoch,
            style: (stroke: (paint: rgb("#0F6E56"), thickness: 0.8pt, dash: "dotted")))

          plot.add(
            val-acc,
            label: [Validation accuracy],
            style: (stroke: (paint: rgb("#534AB7"), thickness: 1.4pt)),
            mark: "o",
            mark-size: 0.15,
            mark-style: (fill: rgb("#534AB7"), stroke: none),
          )
          plot.add(
            val-f1,
            label: [Validation F1],
            style: (stroke: (paint: rgb("#854F0B"), thickness: 1.2pt, dash: "dashed")),
            mark: "x",
            mark-size: 0.15,
            mark-style: (stroke: rgb("#854F0B")),
          )
        }
      )
    }),
  ),
  caption: [
    Training loss and validation metrics over 5 epochs.
    Dashed vertical lines mark epoch boundaries.
    The dotted green line marks the best checkpoint
    (epoch #h(0pt)2, accuracy #h(0pt)89.7%).
  ],
)
